### ISSUE TITLE
@RequestInject在非Controller类中注入的对象不正确

### ISSUE THREAD

**Issue by Eno-CN** [Yurunsoft/imi#120]
**问题描述**
　　创建`UserSession`类用于获取当前用户会话信息（该会话信息在`UserSession::__init()`中初始化），在某非Controller类中使用注解`@RequestInject`将`UserSession`类注入到成员变量中去，但在该类中调用该成员变量时无法获取到用户会话信息。

**补充**
　　在某Controller类中使用注解`@RequestInject`进行注入时，能获取到用户会话信息。
　　任何类中使用`RequestContext::getBean('UserSession')`方式进行调用时，能获取到用户会话信息。

**推测**
　　可能使用注解时，未自动调用`UserSession::__init()`进行初始化？

**期望**
　　在任何类中使用注解`@RequestInject`时，均能有效获取注入的上下文对象。

**Comment by Yurunsoft** [comment]
`@RequestInject`现在也不能在控制器里用了，只要是全局`@Inject`或`App::getBean()`的对象里，都不能用，因为只会注入一次

**Comment by Eno-CN** [comment]
好的 所以后面调用上下文就只用`RequestContext::getBean()`对吧？

> `@RequestInject`现在也不能在控制器里用了，只要是全局`@Inject`或`App::getBean()`的对象里，都不能用，因为只会注入一次
