### ISSUE TITLE
命令行参数输入功能增强

### ISSUE THREAD

**Issue by NHZEX** [Yurunsoft/imi#130]
新问题，要定义选项如下
```
  /**
   * @CommandAction(name="cleanup", description="清理过期缓冲数据")
   * @Option(name="dry-run", type=ArgType::BOOL, default=false, comments="尝试运行")
   * @Lockable(id="collect-cleanup")
   */
```
imi 当前的传参方式仅对全小写或者驼峰支持，其他命名就比较麻烦了。
如果我用`symfon`原生方式获取，`imi`的`BOOL`类型并不兼容，还是得需要支持`InputOption::VALUE_NONE`才行

======= 旧问题 ========
定义一下命令行声明
```
  /**
   * @CommandAction(name="sync", description="同步缓存数据到主库")
   * @Option(name="info", type=ArgType::BOOL, default=true, comments="查看信息")
   * @Option(name="force", shortcut="f", type=ArgType::BOOL, default=false, comments="force")
   * @Option(name="rebuild", shortcut="r", type=ArgType::BOOL, default=false, comments="rebuild")
   */
```

问题：选择值可以单纯当开关，不需要输入
启动命令：`vendor/bin/imi-swoole collect/sync --info`
错误信息：`RuntimeException: The "--info" option requires a value.`

需求支持：InputOption::VALUE_NONE选项

**Comment by Yurunsoft** [comment]
https://github.com/imiphp/imi/commit/56f2221b26f367324a93b29c50aa3176a741942f

Bool 类型的参数现在支持了默认开关，无需修改任何代码
