### ISSUE TITLE
http验证错误

### ISSUE THREAD

**Issue by Mjc960512** [Yurunsoft/imi#156]
* 你遇到了什么问题、建议：
@Text注解强类型出现错误

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`
![image](https://user-images.githubusercontent.com/41005585/134604875-dccc31e1-4865-418a-b6a6-720e41909a6e.png)
![image](https://user-images.githubusercontent.com/41005585/134604963-6738d0b4-40f9-4060-b02c-2546a5de0a36.png)
![image](https://user-images.githubusercontent.com/41005585/134604980-82559fe9-7cce-44ea-be4c-0f35724816d2.png)
![image](https://user-images.githubusercontent.com/41005585/134605004-8a2fec44-2338-4b3a-af49-d55d91256355.png)

```
# 粘贴到这里

```

* 如果可以，提供最小可复现代码：

```php
// 你的代码
@Text(name="travel_agency_name", char=true, max="33", message="旅行社名称不能大于33个字符")
```

**Comment by Yurunsoft** [comment]
更新 `2.0.x-dev` 后尝试

**Comment by Mjc960512** [comment]
问题已解决
