### ISSUE TITLE
有个与项目无关的疑问

### ISSUE THREAD

**Issue by wi1dcard** [Yurunsoft/IMI#2]
您好，关注 IMI 很久，看了下您的 Profile，也有我认识的朋友，不知作者现在在无锡哪家公司？方便透露一下吗，希望能够结识大佬 🤝

**Comment by Yurunsoft** [comment]
野鸡公司，不值一提

**Comment by wi1dcard** [comment]
看了下网站，莫非... 大佬也是易语言出身？

**Comment by wi1dcard** [comment]
日常TG，很少用QQ了，不然早就加群了。
