### ISSUE TITLE
imiGetEnv() 改进提议

### ISSUE THREAD

**Issue by Yurunsoft** [Yurunsoft/imi#226]
为了更加方便地使用 env 环境变量，imi 有计划对 `imiGetEnv` 做一些优化。

如果有更好的想法，欢迎讨论。

如果没有异议，将在 2021-12-10 前完成此 issue。

---

1. `\imiGetEnv()` 设为 deprecated，将在下个大版本（也许是 3.0）中移除
2. 增加 `\Imi\Env` 类，增加 `Imi\Env::get()` 方法作为新的读取环境变量方法，参数和返回值同 `\imiGetEnv()`。
3. 增加 `\Imi\env()`（下面简称`env()`）将 `\Imi\env()`、`\imiGetEnv()` 作为`\Imi\Env::get()`的别名。
4. `env()` 的返回结果值类型会根据 `$default` 参数的值类型，自动转换
支持的类型：`string`、`int`、`float`、`bool`、`array`
5. 当 `$default` 值为默认的 `null` 时，`env()` 的返回结果值类型会根据环境变量值类型智能转换
支持的类型：`string`、`int`、`float`、`bool`、`null`
- 例1：`$default=null`，环境变量 `A=123`，`env('A')` 返回值会自动转为 `int`
- 例2：`$default=null`，环境变量 `A=null`，`env('A')` 返回值是 `null`
6. 增加：`\Imi\Env::str()`、`\Imi\Env::int()`、`\Imi\Env::float()`、`\Imi\Env::bool()`、`\Imi\Env::json()`、`\Imi\Env::list()` 函数，直接获取对应类型的返回值
`\Imi\Env::str()`、`\Imi\Env::int()`、`\Imi\Env::float()`、`\Imi\Env::bool()` 函数定义同 `\Imi\Env::get()`，返回值类型为本身的类型+`null`，如`\Imi\Env::str()`返回值是`?string`
```php
    /**
     * @param mixed $default
     *
     * @return mixed
     */
    public static function json(?string $varname = null, $default = null, bool $localOnly = false, ?bool $associative = true, int $depth = 512, int $flags = \JSON_THROW_ON_ERROR);

    public static function list(?string $varname = null, $default = null, bool $localOnly = false, string $separator = ',', int $limit = \PHP_INT_MAX): ?array;
```
- `\Imi\Env::bool()` 支持识别的值（不区分大小写）：`1`、`0`、`true`、`false`、`on`、`off`
- `\Imi\Env::json()` 支持设定 `json_decode()` 所需参数，默认转换为数组，`json_decode` 失败会抛出异常
- `\Imi\Env::list()` 支持设定分隔符，默认分隔符为`,`，分割失败会抛出异常
- `\Imi\Env::int()`、`\Imi\Env::float()`、`\Imi\Env::bool()` 函数，都支持值类型验证，如果值不符合对应类型的格式，会抛出 `\InvalidArgumentException` 异常
- 

env:
```env
A=123
B=0
C=1,2,3
D=[4, 5, 6]
E=imi
BOOL_TRUE=true
BOOL_FALSE=false
NULL_VALUE=null
EMPTY_VALUE=
```
php:
```php
use Imi\Env;
use function Imi\env;

// Imi\env() 同 Imi\env::get()
env('A'); // 123
env('E'); // imi
env('A', 'default'); // '123'
env('A', 0); // 123
env('A', 3.14); // 123.0
env('A', false); // '123'
env('B', false); // false
env('BOOL_TRUE', false); // true
env('BOOL_FALSE', false); // false
env('C', []); // ['1', '2', '3']
env('D', []); // ['4', '5', '6']
env('NULL_VALUE'); // null
env('NULL_VALUE', 666); // null

Env::str('A'); // '123'
Env::int('A'); // 123
Env::int('E'); // 抛出异常
Env::int('NULL_VALUE'); // null
Env::float('A'); // 123.0
Env::float('E'); // 抛出异常
Env::float('NULL_VALUE'); // null
Env::bool('A'); // 抛出异常
Env::bool('B'); // false
Env::bool('bool_TRUE'); // true
Env::bool('bool_FALSE'); // false
Env::bool('E'); // 抛出异常
Env::bool('NULL_VALUE'); // null
Env::json('D'); // ['4', '5', '6']
Env::json('NULL_VALUE'); // null
Env::json('EMPTY_VALUE'); // 抛出异常
Env::list('C'); // ['1', '2', '3']
Env::list('NULL_VALUE'); // null
Env::list('EMPTY_VALUE'); // 抛出异常
```

**Comment by NHZEX** [comment]
`envStr` 系列的限定类型转换函数建议加上严格类型异常。

**Comment by Yurunsoft** [comment]
> `envStr` 系列的限定类型转换函数建议加上严格类型异常。

已加上
