### ISSUE TITLE
workerman 守护进程 redis消息队列worker进程没有成功启动

### ISSUE THREAD

**Issue by mrlovables** [Yurunsoft/imi#238]
* 你遇到了什么问题、建议：
开启了redis消息队列后 用vendor/bin/imi-workerman workerman/start -d启动 消息队列的worker进程没有启动

**Comment by Yurunsoft** [comment]
是 Workerman 对全局变量 `$argv` 做了修改，现已修复：https://github.com/walkor/workerman/pull/708

imi-workerman 也做了兼容修复，可以更新到 `2.0.x-dev` 试一下
