### ISSUE TITLE
redis队列中数据库gone away

### ISSUE THREAD

**Issue by mrlovables** [Yurunsoft/imi#245]
* 你遇到了什么问题、建议：
workerman-gateway环境下数据库长时间连接后,队列里执行数据库查询就报 Packets out of order ,然后数据库就gone away断开连接,无法重连
[http://snappyimages.nextwavesrl.netdna-cdn.com/img/374b52ddb54138bb25b1969d8bd40480.png](url)

**Comment by Yurunsoft** [comment]
是运行在 swoole 还是 workerman 模式？

**Comment by Yurunsoft** [comment]
两种模式的连接配置，都建议开启：`heartbeatInterval`、`checkStateWhenGetResource` 其中之一。

另外你用的什么版本不清楚，请按照规范提问。

v2.0.18 版本开始数据库操作增加断线错误码判断，自动关闭连接

**Comment by mrlovables** [comment]
PHP 8.1.1 (cli) (built: Dec 25 2021 10:49:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.4
Built => Dec 25 2021 11:14:26
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1k  FIPS 25 Mar 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
[1]  - 1071629 done       php -v
[2]  + 1071630 done       php --ri swoole
imiphp/imi                         v2.0.18  imi 是一款支持长连接微服务分布式的 PHP 开发框架，它可以�...
imiphp/imi-access-control          v2.0.7   imi 框架的权限控制组件
imiphp/imi-apidoc                  v2.0.5   imi 框架 HTTP API 文档生成器，支持 Swagger！
imiphp/imi-jwt                     v2.0.5   在 imi 框架中非常方便地接入 jwt
imiphp/imi-queue                   v2.0.13  imi 框架的队列组件，使用 Redis 作为持久化
imiphp/imi-snowflake               v2.0.4   imi 框架的雪花算法生成组件
imiphp/imi-swoole                  v2.0.14  imi swoole component
imiphp/imi-workerman               v2.0.11  imi workerman component
imiphp/imi-workerman-gateway       v2.0.6   imi workerman gateway component

workerman模式,是2.0.18的版本, heartbeatInterval设置的60秒,周末挂了两天,问题又复现了,之前提的数据库gone away之后接口会挂掉,现在更新2.0.18后,接口不会挂,但是队列里面挂了并不会重连

**Comment by Yurunsoft** [comment]
已修复，可以更新 2.0.x-dev 尝试
