### ISSUE TITLE
网关模式发送大数据异常

### ISSUE THREAD

**Issue by lizuowang** [Yurunsoft/imi#298]
* 你遇到了什么问题、建议：

网关+swoole 模式下向客户端发送数据出现一下问题
1.单个3m数据数据无法发送（网关+workerman 模式可发送）
2.发送多个300k数据 只有前4个数据能发送（网关+workerman 模式也有这个问题）

本地swoole模式 无以上问

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里

```

* 如果可以，提供最小可复现代码：

```php
// 你的代码

```

**Comment by Yurunsoft** [comment]
这边2个问题都无法复现，你的客户端是浏览器吗？

**Comment by Yurunsoft** [comment]
经排查是因为服务器循环发送数据给客户端，导致塞满发送缓冲区。

**解决办法：**

如果你是 Workerman，可以在入口文件中加上：

```php
// 发送缓冲区大小，单位：字节。可以根据需要调整，不建议设置得很大，会浪费内存
\Workerman\Connection\TcpConnection::$defaultMaxSendBufferSize = 2 * 1024 * 1024;
```

如果你是 Workerman Gateway，可以在服务器配置中的 `configs` 加上相应配置：

```php
[
    'gateway' => [
        'namespace'   => 'Imi\WorkermanGateway\Test\AppServer\Gateway',
        'type'        => Imi\WorkermanGateway\Workerman\Server\Type::GATEWAY,
        'socketName'  => 'websocket://0.0.0.0:8081', // 网关监听的地址
        'configs'     => [
            'lanIp'           => '127.0.0.1',
            'startPort'       => 12900,
            'registerAddress' => '127.0.0.1:13004',
            // 发送缓冲区大小，单位：字节。可以根据需要调整，不建议设置得很大，会浪费内存
            'sendToClientBufferSize' => 2 * 1024 * 1024,
        ],
    ],
]
```

修复 Workerman 触发 onError 事件没有默认记录日志：https://github.com/imiphp/imi/commit/c7d25a7b3e1914e597396487ca30942268a40448
