### ISSUE TITLE
介绍一下如何实现代码热更新呗

### ISSUE THREAD

**Issue by myfengstyle** [Yurunsoft/imi#33]
介绍一下如何实现代码热更新呗

**Comment by Yurunsoft** [comment]
如果不涉及注解，很简单，只需要重启 Worker 进程即可。

而涉及注解的热更新比较麻烦，可以参考 imi 的热更新进程代码。

<https://github.com/Yurunsoft/imi/blob/dev/src/HotUpdate/HotUpdateProcess.php>

**Comment by myfengstyle** [comment]
比用 inotify性能好吗

**Comment by Yurunsoft** [comment]
> 比用 inotify性能好吗

imi 的热更新支持 File、Inotify 两种监测模式。

你提到的 Inotify 是用来监测是否有文件改动。

imi 的热更新是检测到文件有改动后，去更新注解缓存，然后重启 Worker 进程

**Comment by myfengstyle** [comment]
好吧有通过openvc实现证件照生成换底色的功能吗，https://phpopencv.org/zh-cn/docs/how_to_scan_images.html    https://github.com/kailaisun/face_gui/blob/master/Openimg/head.py

**Comment by Yurunsoft** [comment]
可以用第三方包来实现这些具体功能，imi 是一个网络通讯协程应用开发框架

**Comment by myfengstyle** [comment]
没找到第三方包呢

**Comment by Yurunsoft** [comment]
没有包可以通过命令行调用来做，图像处理业务不在 imi 的职责范围哦。。
