### ISSUE TITLE
数据库连接池设置了表前缀prefix属性，用ORM生成MODEL查询出来的SQL并没有带表前缀以致SQL出错

### ISSUE THREAD

**Issue by mp5a6mg** [Yurunsoft/imi#353]
如配置：'prefix'   =>'dt_'
用ORM查询则报错：SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.user' doesn't exist
正确的表应该是database.dt_user

**Comment by Yurunsoft** [comment]
`imiphp/imi` 的版本更新到 `dev-fix-353` 试一下是否解决了
