### ISSUE TITLE
建议加上功能点

### ISSUE THREAD

**Issue by ijackwu** [Yurunsoft/imi#36]
1、加上请求接口超时字段配置
2、比如服务起来需要调用一下接口通知做服务发现，服务关闭做下通知关闭。

**Comment by loyating** [comment]
文档：[最大请求执行时间](https://doc.imiphp.com/components/httpserver/maxExecuteTime.html)

**Comment by ijackwu** [comment]
@loyating 搞错了，应该提到imi-grpc那边去，grpc请求没有最大请求时间

**Comment by loyating** [comment]
一样的都是加个中间件，自己实现一个就行
