### ISSUE TITLE
请完善 imi-queue 的 isCluster 判断，支持较低版本的 imi v1.2.x

### ISSUE THREAD

**Issue by imzhi** [Yurunsoft/imi#369]
imiphp/imi-queue 这个库的判断条件需要完善。

需要完善的类 ``RedisQueueDriver``：
![image](https://user-images.githubusercontent.com/2304019/176625917-2453ebe9-5c10-46c4-b200-9e48586914f3.png)

用的 imi 版本是 v1.2.12，Redis 类里没有 isCluster 方法，所以需要加上 method_exists 的判断：
![image](https://user-images.githubusercontent.com/2304019/176626299-4a237b1c-bc37-4dd7-bc01-c4a5024f894f.png)

**Comment by Yurunsoft** [comment]
imi 1.3 和 1.2 兼容，imi 可以更新到 1.3，然后用 imi-queue v1.2.4
