### ISSUE TITLE
运行实例提示错误

### ISSUE THREAD

**Issue by myfengstyle** [Yurunsoft/imi#37]
PHP Warning:  exec() has been disabled for security reasons in /data/wwwroot/imi/project-http/vendor/yurunsoft/imi/src/Listener/Init.php on line 29
PHP Warning:  implode(): Invalid arguments passed in /data/wwwroot/imi/project-http/vendor/yurunsoft/imi/src/Listener/Init.php on line 42

PHP Warning:  exec() has been disabled for security reasons in /data/wwwroot/imi/project-http/vendor/yurunsoft/imi/src/Listener/Init.php on line 29
PHP Warning:  implode(): Invalid arguments passed in /data/wwwroot/imi/project-http/vendor/yurunsoft/imi/src/Listener/Init.php on line 42

**Comment by Yurunsoft** [comment]
不要禁用`exec()`再试试
