### ISSUE TITLE
命令行模型生成问题

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#38]
`./vendor/bin/imi generate/model -namespace "ImiApp\\Models\\Test" -pollName "test"`

多个条件不是这样写的么？当我注释掉配置文件中的`defaultPool` 就会报错，无法获取到传入的连接池，生成的模型中也没有pool 
![image](https://user-images.githubusercontent.com/25193846/73725249-f6709b80-4767-11ea-82c6-4d2143f98e9f.png)

**Comment by Yurunsoft** [comment]
是`poolName`不是`pollName`

**Comment by Denny-w** [comment]
我打错了，但是生成出来之后，Base里面的注解还是没有连接池名称

**Comment by Yurunsoft** [comment]
> 我打错了，但是生成出来之后，Base里面的注解还是没有连接池名称

已在`dev`版本中修复，可以把`composer.json`里imi的版本改为`dev-dev`，然后执行`composer update`，再次尝试。

**Comment by Denny-w** [comment]
好 谢谢
