### ISSUE TITLE
多个项目的热更新只有一个生效？

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#39]
![image](https://user-images.githubusercontent.com/25193846/73735766-bd8df200-477a-11ea-95bc-c00d25680fdf.png)
![image](https://user-images.githubusercontent.com/25193846/73735811-cbdc0e00-477a-11ea-8436-efb2601d4420.png)
![image](https://user-images.githubusercontent.com/25193846/73735841-d5657600-477a-11ea-83d6-b33b9dfba313.png)
两个项目只有一个修改代码有反应

**Comment by Yurunsoft** [comment]
没有的那个执行下`composer update`看看，是否是旧版本，今天发布的稳定版本修复了进程内输出内容看不到的问题

**Comment by Denny-w** [comment]
好 谢谢
