### ISSUE TITLE
并发大的时候提示 AsyncPool [maindb] getResource timeout

### ISSUE THREAD

**Issue by dxasqw** [Yurunsoft/imi#391]
* 你遇到了什么问题、建议：

并发大的时候提示 AsyncPool [maindb] getResource timeout

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里

```

* 如果可以，提供最小可复现代码：

```php
// 你的代码

```

**Comment by dxasqw** [comment]
'waitTimeout'     => 3000,

配置超时加到3秒正常了

**Comment by dxasqw** [comment]
配置超时加到3秒正常了

**Comment by Yurunsoft** [comment]
可以增加连接池的最大连接数量、超时时间，如果还是报这个错误建议考虑扩容服务器或者限流
