### ISSUE TITLE
orm查询获取不到连接池

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#40]
![image](https://user-images.githubusercontent.com/25193846/73747430-6267f980-4792-11ea-8717-5c3e34035ed6.png)
![image](https://user-images.githubusercontent.com/25193846/73747508-888d9980-4792-11ea-8a12-b50a416402f1.png)
![image](https://user-images.githubusercontent.com/25193846/73747581-ab1fb280-4792-11ea-9be6-9643f0402644.png)
orm查询时候获取不到Base里面的连接池

**Comment by Yurunsoft** [comment]
谢谢反馈，已经修复，用最新的 `dev` 版本再试一下

**Comment by Denny-w** [comment]
![image](https://user-images.githubusercontent.com/25193846/73809134-350c6180-480d-11ea-96ae-1f3fb48f7682.png)
未走model的query 走的是db的query

**Comment by Yurunsoft** [comment]
模型的数据库查询都是走的`Db`没错，这个报错是在最新dev下出现的吗？

**Comment by Denny-w** [comment]
是的，刚进去看了下源码跟刚才提交记录里的是一样的，
![image](https://user-images.githubusercontent.com/25193846/73809565-9c76e100-480e-11ea-9f56-1a4c8a024a2e.png)
meta 获取到的元数据打印出来好像没有注解里面的连接池吧

**Comment by Yurunsoft** [comment]
是模型生成那边的问题，更新下，再重新生成下模型吧

**Comment by Denny-w** [comment]
可以了  谢谢
