### ISSUE TITLE
配置文件中的env获取？

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#41]
![image](https://user-images.githubusercontent.com/25193846/73817851-fb485480-4826-11ea-9ff8-b01a14eb72fb.png)
![image](https://user-images.githubusercontent.com/25193846/73817950-3054a700-4827-11ea-9594-7e95543838db.png)

配置文件读取env配置无反应，配置的非本地，报错连接的是本地的

**Comment by Yurunsoft** [comment]
可以看一下imi中env的使用方式：<https://doc.imiphp.com/base/config.html>

目前 imi 的 env 加载顺序在 config 之后，我考虑了一下确实不对，下个版本调整一下

**Comment by Denny-w** [comment]
看到文档了，但是那样的话就会写的很多啊，相当于是要一个一个的去设置这样重复的也不好复用
![image](https://user-images.githubusercontent.com/25193846/73819001-83c7f480-4829-11ea-9d93-e143090beaf2.png)

**Comment by Yurunsoft** [comment]
是的，调整加载顺序后就可以复用了

**Comment by Yurunsoft** [comment]
@Denny-w 可以试试，现在可以了
