### ISSUE TITLE
异常捕获问题

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#42]
在我抛出异常的时候，
![image](https://user-images.githubusercontent.com/25193846/74213658-30e0b800-4cd5-11ea-9832-decfa521fcaa.png)
![image](https://user-images.githubusercontent.com/25193846/74213667-4229c480-4cd5-11ea-8aec-736ebd7a9402.png)
我这样设置了就是所有的异常都会抛出了，那我只想抛出我自己的异常怎么办？框架内部的异常不想展示出来

**Comment by Yurunsoft** [comment]
可以参考`Imi\Server\Http\Error\JsonErrorHandler`类，自己编写一个处理类

**Comment by Denny-w** [comment]
好
