### ISSUE TITLE
orm问题

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#43]
为什么`orm`调用`getArray()`返回的就是数组里面又是对象，`Db`操作`getArray()`返回的就是数组？

**Comment by Yurunsoft** [comment]
`getArray()`这个方法是获取数组列表，所在类是`Imi\Db\Query\Result`

这么写返回的结果无论是单条或多条，都是模型对象：

```php
XXXModel::query()->select()->getArray();
```

这么写，永远返回数组，字段按数据库命名原样返回：

```php
XXXModel::dbQuery()->select()->getArray();
```

**Comment by Denny-w** [comment]
谢谢，明白了
