### ISSUE TITLE
容器对象类问题？

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#45]
我创建了一个类并且声明了`@Bean() `,我这个类不能作为子类使用么，继承父类就会报错
![image](https://user-images.githubusercontent.com/25193846/74317071-ad4ac800-4db5-11ea-8e29-f45617e3ccd3.png)

**Comment by Yurunsoft** [comment]
可以继承的，构造方法参数不一样，还是没有实例化时候传参？
