### ISSUE TITLE
打包执行报错

### ISSUE THREAD

**Issue by liu-jiangyuan** [Yurunsoft/imi#460]
按照这个操作步骤操作后,出现问题
![image](https://user-images.githubusercontent.com/20334310/204725953-7bdb63ae-5323-4edc-9e02-cd9905ce7bc4.png)

**Comment by Yurunsoft** [comment]
`vendor` 目录的文件是否都打包进 phar 了？

**Comment by liu-jiangyuan** [comment]
> `vendor` 目录的文件是否都打包进 phar 了？

打了,但是我刚发现了个问题,打好phar的包以后,持续一会这个包里面就空了,什么都没有,就一个空空的phar文件

**Comment by liu-jiangyuan** [comment]
> `vendor` 目录的文件是否都打包进 phar 了？

docker 环境下打包失败,打包结束,一下下然后phar文件就空了

**Comment by Yurunsoft** [comment]
打包失败后是空phar文件是正常的，docker 下读写文件失败可能和共享文件系统有关

**Comment by liu-jiangyuan** [comment]
> 打包失败后是空phar文件是正常的，docker 下读写文件失败可能和共享文件系统有关

那我就定位不到了,按照默认的配置打包也不行,一样的报错

**Comment by Yurunsoft** [comment]
试试把项目代码全部放到docker容器里，如果可以启动服务，那就再试试打包是否可以成功

**Comment by liu-jiangyuan** [comment]
> 试试把项目代码全部放到docker容器里，如果可以启动服务，那就再试试打包是否可以成功

一直是把整个项目挂载到docker,源码启动一切正常,打包后执行就报错

**Comment by Yurunsoft** [comment]
不是挂载，我是说代码都复制到容器内部的文件系统里试试

**Comment by liu-jiangyuan** [comment]
> 不是挂载，我是说代码都复制到容器内部的文件系统里试试

不用挂在目录,换成容器内任意目录打包都可以,就挂载目录打包不行

**Comment by Yurunsoft** [comment]
那基本上就是docker挂载的共享文件系统的锅，跟框架没啥关系

**Comment by liu-jiangyuan** [comment]
> 那基本上就是docker挂载的共享文件系统的锅，跟框架没啥关系

我来看看是不是挂在权限的问题
