### ISSUE TITLE
模型操作不是事务进行么?

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#47]
![image](https://user-images.githubusercontent.com/25193846/74644528-5d06a800-51b1-11ea-9816-e31f6361b522.png)
直接在第一个完成之后就有第二个就去直接插入第二个了,中间如果断了不就数据不统一了,没有进行事务处理么

**Comment by Yurunsoft** [comment]
可以在外面的业务逻辑里用事务

代码方式：
```php
Db::transContext(function(IDb $db){
 
});
```

注解方式写在方法上：`@Transaction`，当然前提这个对象是`@Inject`注入或者`App::getBean()`实例化出来的。

文档：<https://doc.imiphp.com/components/db/index.html>

**Comment by Denny-w** [comment]
开启db的事务,里面在执行orm的也可以?

**Comment by Yurunsoft** [comment]
可以的，orm里的数据库操作，走的就是 Db

**Comment by Denny-w** [comment]
好的,另外大佬,guzzle-swoole这个里面还有一个问题.一直没搞懂

**Comment by Denny-w** [comment]
好的,另外大佬,guzzle-swoole这个里面还有一个问题.一直没搞懂

**Comment by Yurunsoft** [comment]
那个问题挺奇怪的，我解决不了，哈哈，我再来问问swoole开发组大佬
