### ISSUE TITLE
关于验证器的问题?

### ISSUE THREAD

**Issue by Denny-w** [Yurunsoft/imi#48]
![image](https://user-images.githubusercontent.com/25193846/74648229-35ffa480-51b8-11ea-9293-48f2b3c048a2.png)
当我使用这个方法自定义验证的时候,我如何自定义消息返回呢?比如我一个方法里面会有三条判断,对应是三个错误?我看示例也都是返回一个`bool`

**Comment by Yurunsoft** [comment]
可以直接抛异常，或者三条判断分三个方法来做，一般抛异常就行了。
