### ISSUE TITLE
aop方法会重复执行的问题

### ISSUE THREAD

**Issue by atonemi** [Yurunsoft/imi#480]
* 你遇到了什么问题、建议：

环境：MacOs swoole-cli 5.0.1

![942BA2B638CA6859C82C83FEAC6587FC](https://user-images.githubusercontent.com/75244754/226624587-96776ef4-5862-4b8f-a9e1-d5d69b5a5d0d.jpg)

这个deny如果我把里面的路径写错  aop里面的代码第一次请求会执行两次, 后续请求则只会执行一次
如果写对  aop里面的代码第一次请求会执行一次  后续请求就不会再进来了

[aop-test.zip](https://github.com/imiphp/imi/files/11028972/aop-test.zip)

运行后测试请求地址：http://127.0.0.1:9504/super/ac/member/login

润哥辛苦

**Comment by Yurunsoft** [comment]
第一次执行是因为构造函数执行，可以把 `__construct` 也放进 `deny`
