### ISSUE TITLE
mysql json字段不支持key为中文

### ISSUE THREAD

**Issue by luobutouzi** [Yurunsoft/imi#493]
* 你遇到了什么问题、建议：
mysql json字段不支持key为中文：
![图片](https://user-images.githubusercontent.com/41530685/231105840-f63cca1f-61fa-4595-a79e-ea63df41319e.png)

构建update语句：
![图片](https://user-images.githubusercontent.com/41530685/231105974-df2570ab-4cf0-4fb9-8936-9b4b673c6b6a.png)
需要双引号包裹 "中文"，字段外面一层用的"，导致冲突

**Comment by Yurunsoft** [comment]
试一下这个 PR 修改的代码是否解决了你的问题
