### ISSUE TITLE
put请求方法post和getParsedBody都获取不到参数

### ISSUE THREAD

**Issue by my38778570** [Yurunsoft/imi#521]
![6707e81cf572d8646ffcb30644c46ab](https://github.com/imiphp/imi/assets/46992482/d1b88aec-e363-43ac-a408-ca5b4d2df346)
![c5cf559918cb4c5deb9a4d68a11f565](https://github.com/imiphp/imi/assets/46992482/61896da4-c1b9-4183-be48-cf1959389ecc)
![6db40f858b8bab9a63206928d43aa49](https://github.com/imiphp/imi/assets/46992482/801d5ccb-b524-4aa7-9987-3ffad6e54984)

**Comment by Yurunsoft** [comment]
已修复，可以先使用 2.1.x-dev 版本或等待下次发布
