### ISSUE TITLE
验证器BUG及建议优化

### ISSUE THREAD

**Issue by angel-wangchuan** [Yurunsoft/imi#53]
BUG:
验证器, @Integer 方式验证数据存在漏洞,传字符串也可以验证通过;

建议优化:
现在的验证器,功能不是很好用,希望添加下 验证场景 方式验证参数,可以借鉴下TP的验证方式
以下是TP5.1的验证方式
class Tencent extends Validate {
    // 验证参数
    protected $rule = [
        'num' => 'require',
        'content' => 'require'
    ];
    // 验证错误文案
    protected $message = [
        'num.require' => 'num不能为空',
        'content.require' => '内容不能为空'
    ];
    // 验证tag
    protected $scene = [
        'postOften'  =>  ['num','content']
    ];
}
$validate = new Tencent;
$validate->scene('postOften')->check($data);

**Comment by Yurunsoft** [comment]
问题已经修复，场景验证也已支持，具体可以查看文档：https://doc.imiphp.com/components/validation/index.html
