### ISSUE TITLE
关于定时任务的相关问题

### ISSUE THREAD

**Issue by linfcom** [Yurunsoft/imi#54]
你好！
我创建了一个TestTask类，并使用Cron注解设置定时任务为1秒执行一次，超时时间10秒。但是我在使用过程中定时任务执行完成后需要等待超时才会结束本次事件，请问一下这是我代码的问题吗？

![image](https://user-images.githubusercontent.com/45063822/79496003-1cfc5e00-8058-11ea-829a-22e617aa87f7.png)
![image](https://user-images.githubusercontent.com/45063822/79496167-5208b080-8058-11ea-95bc-e23627bb4ace.png)

**Comment by Yurunsoft** [comment]
如果实现`ITaskHandler`接口需要手动上报定时任务结果

需要在类中`use TWorkerReport;`

然后上报定时任务结果：

```php
$this->reportCronResult('任务ID', true, '');
```

---

实现`ICronTask`接口，无需手动上报。

文档参考：<https://doc.imiphp.com/components/task/cron.html>

> 之前文档中没有细说，现已补充
