### ISSUE TITLE
imi-swoole 获取MasterPid递归调用

### ISSUE THREAD

**Issue by z83760037** [Yurunsoft/imi#544]
* 你遇到了什么问题、建议：

![image](https://github.com/imiphp/imi/assets/50696684/bda3e832-270f-4363-b1df-d5c39f2ea6d3)

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里

```

* 如果可以，提供最小可复现代码：

```php
// 你的代码

```

**Comment by Yurunsoft** [comment]
已修复，可以先用前一个稳定版或`2.1.x-dev`，预计本周五发布一个版本。
