### ISSUE TITLE
mqtt服务器添加自定义上线事件后监听不到事件触发

### ISSUE THREAD

**Issue by fangdayts** [Yurunsoft/imi#549]
* 你遇到了什么问题、建议：
### **mqtt服务器添加自定义上线事件后监听不到事件触发，并且热更新会出现[FATAL ERROR]: all coroutines (count: 1) are asleep - deadlock!**

![F6 I~(UL(( (7 2O7QI821A](https://github.com/imiphp/imi/assets/133741605/8b445278-47d8-4621-9d5c-32c70bbed9bf)
![NQUM6$H0((LVVC(8L6 N~ H](https://github.com/imiphp/imi/assets/133741605/49a340cc-2d9c-417f-bcab-22bfa6da5700)

![Z)ZQCZ@(7LSZ5U21XP_G@C](https://github.com/imiphp/imi/assets/133741605/debba576-4b5f-4f16-ad05-7a5ff9aa5fe0)

[project-mqtt_87RbGt.tar.gz](https://github.com/imiphp/imi/files/11901685/project-mqtt_87RbGt.tar.gz)

* 如果可以，提供最小可复现代码：

```php
// 你的代码


```

**Comment by Yurunsoft** [comment]
事件监听类命名空间不对，请按照标准规范命名
