### ISSUE TITLE
MQTT服务端长时间运行报错End of stream reached when trying to read 25190 bytes.

### ISSUE THREAD

**Issue by fangdayts** [Yurunsoft/imi#558]
* 你遇到了什么问题、建议：
MQTT服务端运行的时候会出现这个报错
**BinSoul\Net\Mqtt\Exception\EndOfStreamException: End of stream reached when trying to read 25190 bytes. content length=53, position=4 in /data/imi/vendor/binsoul/net-mqtt/src/PacketStream.php:47**

BinSoul\Net\Mqtt\Exception\EndOfStreamException: End of stream reached when trying to read 25190 bytes. content length=53, position=4 in /data/imi/vendor/binsoul/net-mqtt/src/PacketStream.php:47
Stack trace:
#0 /data/imi/vendor/binsoul/net-mqtt/src/PacketStream.php(93): BinSoul\Net\Mqtt\PacketStream->read()
#1 /data/imi/vendor/binsoul/net-mqtt/src/Packet/PublishRequestPacket.php(32): BinSoul\Net\Mqtt\PacketStream->readString()
#2 /data/imi/vendor/imiphp/imi-mqtt/src/imi/Server/MQTT/DataParser/MQTTDataParser.php(46): BinSoul\Net\Mqtt\Packet\PublishRequestPacket->read()
#3 /data/imi/vendor/imiphp/imi/src/Server/DataParser/DataParser.php(62): Imi\Server\MQTT\DataParser\MQTTDataParser->decode()
#4 /data/imi/vendor/imiphp/imi-mqtt/src/imi/Server/MQTT/Message/ReceiveData.php(50): Imi\Server\DataParser\DataParser->decode()
#5 /data/imi/vendor/imiphp/imi-mqtt/src/imi/Server/MQTT/Listener/BeforeReceive.php(65): Imi\Server\MQTT\Message\ReceiveData->__construct()
#6 /data/imi/vendor/imiphp/imi/src/Event/TEvent.php(53): Imi\Server\MQTT\Listener\BeforeReceive->handle()
#7 /data/imi/vendor/imiphp/imi/src/Event/TEvent.php(200): Imi\Server\Contract\BaseServer::Imi\Event\{closure}()
#8 /data/imi/vendor/imiphp/imi-swoole/src/Server/TcpServer/Server.php(154): Imi\Server\Contract\BaseServer->trigger()
#9 {main}

**Comment by Yurunsoft** [comment]
请按规定格式反馈问题
