### ISSUE TITLE
热更新间隔抽风，无法正常运行

### ISSUE THREAD

**Issue by skykain** [Yurunsoft/imi#56]
这个问题虽然可以通过手动再起服务解决，但总觉得不爽。

系统：macOS 10.15.4
php：7.4.2
swoole：4.5.0

遇到的情况如下：
基本上平滑重载了几次后,静止一小会，修改某一文件保存，终端上会出现warning，然后会一直卡在 Building runtime

> 2020-05-08 11:08:48 [warning] Not found buildRuntime tool connection /Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/HotUpdate/HotUpdateProcess.php:295
Found 1 changed Files:
/Users/kain/Code/GIT/imi-projects/project-http/ApiServer/Controller/MiddlewareController.php
Building runtime...

log 文件记录：

> 2020-05-08 11:08:48 [warning] Not found buildRuntime tool connection
#0  Imi\HotUpdate\HotUpdateProcess->beginBuildRuntime(array) called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/HotUpdate/HotUpdateProcess.php:185]
#1  Imi\HotUpdate\HotUpdateProcess->run(object) called at [/private/tmp/imi-3ruki8:30]
#2  HotUpdateProcess__Bean__19->{closure}(object) called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/Bean/BeanProxy.php:294]
#3  Imi\Bean\BeanProxy->callOrigin(object, run, array, object) called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/Bean/BeanProxy.php:87]
#4  Imi\Bean\BeanProxy->call(object, run, object, array) called at [/private/tmp/imi-3ruki8:25]
#5  HotUpdateProcess__Bean__19->run(object) called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/Process/ProcessManager.php:112]
#6  Imi\Process\ProcessManager::Imi\Process\{closure}() called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/functions.php:34]
#7  {closure}() called at [/Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/functions.php:18]

定位了下 /private/tmp/imi-3ruki8 文件，文件已经不存在

**Comment by Yurunsoft** [comment]
应该是苹果电脑下的兼容性问题，晚些时候看一下

**Comment by skykain** [comment]
好的

**Comment by Yurunsoft** [comment]
我这边尝试了一下，启动后修改文件，触发热更新几次。然后放置了半小时，再修改文件，触发热更新。没有你所说的报错和卡住问题，是否需要等更久的时间？

**Comment by skykain** [comment]
我这边是启动服务 `vendor/bin/imi server/start` 后静置 2~3 分钟都会出现，修改下文件保存就会出现 ...... 好迷，表示已经接受手动重启操作了 :joy::joy::joy:


> [System]
System: Darwin
CPU: 8 Cores
Disk: Free 154.166 GB / Total 465.627 GB

> [Network]
ip@en0: 192.168.1.100

> [PHP]
Version: v7.4.2
Swoole: v4.5.0
imi: v1.2.4
Timezone: PRC

> Server start
WorkerNum: 8, TaskWorkerNum: 0
[Http] main; listen: 0.0.0.0:8080
Process [hotUpdate] start
App Inited
Found 1 changed Files:
/Users/kain/Code/GIT/imi-projects/project-http/ApiServer/Controller/MiddlewareController.php
Building runtime...
2020-05-09 10:47:51 [warning] Not found buildRuntime tool connection /Users/kain/Code/GIT/imi-projects/project-http/vendor/yurunsoft/imi/src/HotUpdate/HotUpdateProcess.php:295

**Comment by Yurunsoft** [comment]
我找朋友用苹果电脑测试，我自己用虚拟机跑苹果系统测试，都没有出现你说的这个问题。暂时先记录下来，后面我再想办法

**Comment by skykain** [comment]
:smile::smile:好的，麻烦你了

估计大可能是电脑的问题，之前也遇过一个软件在别的机子上就正常，死活在我机子上运行不了。

**Comment by Yurunsoft** [comment]
imi版本改成dev-dev，你再看看热更新还有问题没，刚刚重构了一下
