### ISSUE TITLE
使用关联插入时报错

### ISSUE THREAD

**Issue by onlyshow** [Yurunsoft/imi#585]
* 我的问题、建议：（必填）
通过UserFriend::newInstance初始化，返回的是其bean对象，instanceof UserFriend 为false
建议使用__getRealClassName获取真实类型判定

* 错误日志：（可选）

```log
ArrayList item must be an instance of app\\Module\\ChangeLog\\Model\\ChangeLogKeyword, array given

```

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里（必填）

```

* 提供最小可复现代码：（可选）

```php
$user->friends->append(
    UserFriend::newInstance(['friend_user_id'=>1]),
    UserFriend::newInstance(['friend_user_id'=>2])
);
```

**Comment by Yurunsoft** [comment]
Bean 对象继承了 `UserFriend` 类，`instance of` 是有用的，你的 `append()` 方法应该是传了数组

**Comment by onlyshow** [comment]
`current($insertList) instanceof ChangeLogKeyword` 我测试时看错了，确实传入数组了。
