### ISSUE TITLE
task 处理高并发问题！

### ISSUE THREAD

**Issue by hetech8** [Yurunsoft/imi#62]
task 处理高并发，应该怎么写？  按百度swoole的写法，imi好像不支持。 高并发会出现线程过多、数据连接过多的错误，导致数据库连接占满，别的程充都连不上，请大神给个思路。

**Comment by Yurunsoft** [comment]
经测试是不开启task进程协程时的问题，可以在`mainServer.config`中配置：

```php
'task_enable_coroutine' =>  true
```
