### ISSUE TITLE
软删除字段默认值为null查询报错

### ISSUE THREAD

**Issue by cyycler** [Yurunsoft/imi#669]
* 我的问题、建议：（必填）
软删除字段默认值为null时(默认值为0的话是没问题) 查询报错

* 错误日志：（可选）

```log
# 如有报错日志请贴到这里
![image](https://github.com/imiphp/imi/assets/42498453/b52f8c7d-a605-4b80-b811-706df88b44b2)

```

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里（必填）

```

* 提供最小可复现代码：（可选）

```php
// 你的代码
![image](https://github.com/imiphp/imi/assets/42498453/1f507210-38cb-4f4f-b11a-8a53bafa0fc0)
![image](https://github.com/imiphp/imi/assets/42498453/70da2c03-713d-477e-a783-f4f358088ecd)

```

**Comment by cyycler** [comment]
![3](https://github.com/imiphp/imi/assets/42498453/79e5bcfe-2426-458b-a670-55aafce8a542)
![2](https://github.com/imiphp/imi/assets/42498453/362d7a16-eae9-4432-a5ff-0494091635e5)
![1](https://github.com/imiphp/imi/assets/42498453/f8304b91-4f85-4900-a028-338b6b0e217d)

**Comment by Yurunsoft** [comment]
你的 MySQL 版本是多少？

**Comment by Yurunsoft** [comment]
原因是 imi 默认禁用了 `\PDO::ATTR_EMULATE_PREPARES`

可以在连接池配置的`resource`里配置：

```php
[
    'options' => [
        \PDO::ATTR_EMULATE_PREPARES  => true
    ]
]
```

**Comment by cyycler** [comment]
加上可以了

**Comment by Yurunsoft** [comment]
问题已解决，下个版本无需修改配置
