### ISSUE TITLE
请求接口验证字段时是否可以不用传参

### ISSUE THREAD

**Issue by rironlin** [Yurunsoft/imi#69]
请求接口验证字段时，是否可以考虑不用传参？请求接口如果接受参数过多且都需要验证时，传入参数太多，导致代码臃肿。个人见解，如果现目前的方式更符合规范，可以不用理睬这条建议

**Comment by Yurunsoft** [comment]
可以不用传参的，`name`使用`$get.id`、`$post.id`等方式就可以不用传参
文档：<https://doc.imiphp.com/components/httpserver/validation.html>
