### ISSUE TITLE
使用easywechat包报错 swoole_curl_setopt(): CURLOPT_HTTP_VERSION[3] is not supported

### ISSUE THREAD

**Issue by cyycler** [Yurunsoft/imi#692]
* 我的问题、建议：（必填）
在imi中使用包easywechat (版本:6.7) 报错 swoole_curl_setopt(): CURLOPT_HTTP_VERSION[3] is not supported 需如何解决

* 错误日志：（可选）

```log
# 如有报错日志请贴到这里

```

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里（必填）

```

* 提供最小可复现代码：（可选）

```php
// 你的代码

```

**Comment by sy-records** [comment]
重新编译 swoole 扩展，启用对 SWOOLE_HOOK_NATIVE_CURL 的支持
https://wiki.swoole.com/zh-cn/#/environment?id=-enable-swoole-curl

**Comment by cyycler** [comment]
> 重新编译 swoole 扩展，启用对 SWOOLE_HOOK_NATIVE_CURL 的支持 https://wiki.swoole.com/zh-cn/#/environment?id=-enable-swoole-curl

感谢
