### ISSUE TITLE
疑问🤔️

### ISSUE THREAD

**Issue by wi1dcard** [Yurunsoft/IMI#7]
<https://github.com/Yurunsoft/IMI/compare/6f55e94cb5...efc6866e8c#diff-669d2749632508032ec7e98929e77b52R28>

不知为何要使用下划线？

See: <https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#42-properties>

> Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.

**Comment by Yurunsoft** [comment]
![image](https://user-images.githubusercontent.com/20104656/46242312-e4574e00-c3f9-11e8-92e8-c9e1552b6bd5.png)

看不到东西

**Comment by wi1dcard** [comment]
<https://github.com/Yurunsoft/IMI/blob/efc6866e8cb58066f183c47134242933f3994e0d/src/Event/EventParam.php#L22>

**Comment by Yurunsoft** [comment]
构造方法里传进来的`$data`，里面的键可能会有冲突，所以内置的属性加下划线，避免一般情况下的冲突

**Comment by wi1dcard** [comment]
懂了，在子类里定义属性。这个 EventParam 的设计有点像 .NET。

**Comment by Yurunsoft** [comment]
主要还是活用php的数组，虽然强类型好维护，但是也不能太死板，去完全按照其他语言的套路写。该用php数组的地方还得用，这是php的优势
