### ISSUE TITLE
windows docker 容器 reloading server卡住

### ISSUE THREAD

**Issue by cj19891031** [Yurunsoft/imi#74]
`Found 1 changed Files:
/data/www/strong/project-http/ApiServer/Controller/IndexController.php
Building runtime...
Build time use: 0.27699112892151 sec
Reloading server...
2021-01-19 07:24:56 [info] Server is reloading all workers now
Found 1 changed Files:
/data/www/strong/project-http/ApiServer/Controller/IndexController.php
Building runtime...
Build time use: 0.28880381584167 sec
Reloading server...`

我是在windows下的docker容器跑的，发现第二次修改文件后必定会卡住，并且没有任何报错

**Comment by Yurunsoft** [comment]
已解决，尝试一下更新到`dev-dev`版本
