### ISSUE TITLE
vlucas/phpdotenv 依赖版本更新问题

### ISSUE THREAD

**Issue by NHZEX** [Yurunsoft/imi#75]
vlucas/phpdotenv >= 3 之后的版本定义了合法的键名称检查，无法与现有的配置定义兼容，有更新版本可能性么?

错误信息：```Failed to parse dotenv file due to an invalid name. Failed at [@app.yurun].```

https://github.com/vlucas/phpdotenv/blob/1bdf24f065975594f6a117f0f1f6cabf1333b156/src/Parser.php#L81-L91

**Comment by Yurunsoft** [comment]
已更新版本，并且兼容
