### ISSUE TITLE
模型的`json`类型需求传入序列化参数

### ISSUE THREAD

**Issue by NHZEX** [Yurunsoft/imi#77]
需求是设置`json_encode`的`options`选项，以加上`JSON_UNESCAPED_SLASHES  | JSON_UNESCAPED_UNICODE `选项，使序列化后的数据可读性好些，体积减小。

目前解决：不用imi的json类型，覆盖get/set实现需求，

PS：平时使用json序列化时都加上一些常用选项，发现imi的`json`序列化大多都无法定制options选项（或者考虑把这些好用的选项硬编码），这个可考虑个方案？

**Comment by Yurunsoft** [comment]
可以，晚点搞一下

**Comment by Yurunsoft** [comment]
已在 v1.2.22 实现，具体详见文档 `@JsonEncode` 注解用法：<https://doc.imiphp.com/components/orm/RDModel.html>
