### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by wolf-leo** [Yurunsoft/imi#82]
驱动是File

value 类型 object

CacheManager::set(‘alias1’, 'key‘,'value',60) ;// 写入正常
CacheManager::has(‘alias1’, 'key‘) ;            // 判断返回true
CacheManager::get(‘alias1’, 'key‘) ;            // 获取返回 "" 空的！！！
why？

**Comment by Yurunsoft** [comment]
<https://doc.imiphp.com/components/cache/file.html>

存对象需要配置：`formatHandlerClass`，对象一般建议用序列化
