### ISSUE TITLE
使用 imi 框架开发的部分项目：看个蛋影视搜索

### ISSUE THREAD

**Issue by wolf-leo** [Yurunsoft/imi#83]
### 看个蛋影视搜索- 全网影视资源搜索平台

![360截图20210326155911140](https://user-images.githubusercontent.com/37436228/112600679-7a925080-8e4c-11eb-8c4e-de1361df3a43.jpg)
**项目介绍**：
从最早的建站初心是为了自己方便！放到网络的以来，当流量越来越大的时候是要考虑升级配置还是重构项目，前几天git上看到imiphp，索性就拿来实践一下，也是简单就重构出了所有页面，模版引擎引入了TP的think-template，整个重构也就一天不到，所以imiphp确实很容易上手！加油！

**Comment by Yurunsoft** [comment]
已经更新到 imi README.md 和官网，感谢支持~
