### ISSUE TITLE
建议orm的操作更加灵活

### ISSUE THREAD

**Issue by Mjc960512** [Yurunsoft/imi#87]
如果真的需要，可以认真写一份提案到issue
* 需要实现的功能
* 为什么要实现，解决什么问题
* 期望如何实现，可以提供API设计和使用demo代码

### 一.需要实现什么样的功能？
例如laravel，tp的关联预加载功能。关联在代码中控制是否查询，以避免浪费不必要的数据库性能。因为一个表可能有很多关联。

### 二.为什么要实现，解决什么问题
orm的关联查询，几乎涵盖了所有开发应用，一对一，一对多在数据库操作中，必然是使用及其高频的，开发项目必然和数据库打交道最多，那关联查询一定逃不掉，现在imi已经有基础关联功能了，但是在关联场景中，有一些内容是肯定逃不过的，举几个例子：

1. 订单查询中查询某个用户，这时候只想要展示用户头像，昵称，手机号。
2. 查询某几个用户的订单时，只希望查询这些用户的前三个订单，需要以树形态展示（有点难以说服我自己这个需求，确实有点难以理解，我一时也没相当，但我记得我经常在with中闭包指定where()）。
3. 对一对多的列表进行排序。
以上这些都是在关联中进行的操作，还有很多场景，老哥你可以想象一下。
所以在关联中，我希望imi可以借鉴一下tp，laravel的关联预加载功能。

### 三.期望如何实现
非常抱歉，api设计我不擅长，我这里只能提供demo使用代码

有时，你可能需要在你关联的查询中添加额外查询条件，就像下面的例子：
```php
$users = Imi\Model\User::with(['posts' => function ($query) {
    $query->where('title', 'like', '%first%');
}])->get();
```

也可以调用其它的 查询构造器 方法进一步自定义预加载操作：
```php
$users = Imi\Model\User::with(['posts' => function ($query) {
    $query->orderBy('created_at', 'desc');
}])->get();
```

**Comment by Yurunsoft** [comment]
目前 imi 不支持 `with` 的用法，而且这确实是刻意的。最初实现模型功能时，也参考了主流框架的实现。之所以没实现，是和 imi 的设计哲学不符。

imi 的模型类里一般不写逻辑代码，模型类的一个对象就代表一条记录，并且所有字段都需要有值（除非你不定义指定的字段）。

刚接触 imi 的开发者可能会对模型类查询器上，加上`->field()`指定字段，这个可以执行，但会导致该字段 json 序列化出来后为 null。

所以一般解决方法推荐的是使用 `模型类::dbQuery()` 来获取查询构建器，这样查询后的结果就是数组了。

需要注意的是，上面说的并不是缺陷，而是设计哲学的不同，也没有好与坏的分别。

---

目前可以考虑增加类似 `with` 的动态用法，但是返回结果也只能是数组，而不会有模型对象。

---

下面针对上面举的例子给出解决方案：

1. 订单查询中查询某个用户，这时候只想要展示用户头像，昵称，手机号。

```php
    /**
     * 用户资料.
     *
     * @Column(virtual=true)
     *
     * @var array
     */
    protected $userInfo;

    /**
     * Get 用户资料.
     *
     * @return array
     */
    public function getUserInfo()
    {
        if (null === $this->userInfo)
        {
            // 实现方法一：模型
            $record = UserModel::find($this->userId);

            return $this->userInfo = [
                'avatar'   => $record->avatar,
                'nickname' => $record->nickname,
                'phone'    => $record->phone,
            ];

            // 实现方法二：查询构建器
            return $this->userInfo = UserModel::dbQuery()->field('avatar', 'nickname', 'phone')->select()->get();
        }

        return $this->userInfo;
    }
```

2. 查询某几个用户的订单时，只希望查询这些用户的前三个订单，需要以树形态展示（有点难以说服我自己这个需求，确实有点难以理解，我一时也没相当，但我记得我经常在with中闭包指定where()）。

```php
    /**
     * 用户前 3 个订单列表.
     *
     * @Column(virtual=true)
     *
     * @var array
     */
    protected $orders;

    /**
     * Get 用户前 3 个订单列表.
     *
     * @return array
     */
    public function getOrders()
    {
        if (null === $this->orders)
        {
            // 实现方法一：模型
            return $this->orders = OrderModel::query()->where('user_id', '=', $this->userId)
                                                      ->order('id', 'desc')
                                                      ->select()
                                                      ->getArray();

            // 实现方法二：查询构建器
            return $this->orders = OrderModel::dbQuery()->where('user_id', '=', $this->userId)
                                                        ->order('id', 'desc')
                                                        ->field('order_number', 'title') // 还可以指定字段
                                                        ->select()
                                                        ->getArray();
        }

        return $this->orders;
    }
```

3. 对一对多的列表进行排序。
以上这些都是在关联中进行的操作，还有很多场景，老哥你可以想象一下。
所以在关联中，我希望imi可以借鉴一下tp，laravel的关联预加载功能。

这个文档有所缺失，`@OneToMany` 注解早已支持了 `order` 参数，用于排序，现已更新文档：<https://doc.imiphp.com/components/orm/relation/index.html>

**Comment by Mjc960512** [comment]
### 下面一些例子，巨佬可以好好思考下

- 一个表，定义了很多关联，例如一个用户关联了资料，订单，收藏了商品，在查询订单的时候，如果和避免将收藏，资料也查询出来（在使用关联功能的情况下进行。）

- 还是上面的需求，但使用虚拟字段进行查询，但若一个表定义了很多虚拟字段，是否可以通过dbQuery()->field()控制显示某些字段，以免将虚拟字段全部查出来，避免没有必要的性能浪费。

- 一对多关联，如果进行统计查询，关联中使用count()和where()，是否有解决方法？(在使用关联的情况下，我知道不使用关联可以做到)

一时间很难想到特别多的应用场景，但应用场景一定不少，这些功能使用with，闭包传参都可以搞定，我相信老哥你也非常抵制996的，因为你在群里经常说的就是，抵制996，一把梭，我觉得你也在考虑灵活性上思考了很久，但没有with的设计，和你说的这些话变得有些违背。

我觉得所谓的哲学和现实情况并不矛盾，你可以考虑下是否可以在兼顾哲学的情况下，将这些恶心人的工作在用imi的时候变得无比轻松，而这种轻松在使用非swoole框架得时候，其实早就实现了，你的框架设计初衷，就是小而快，使用简单却灵活多变，我相信heyerf借鉴laravel也不是头脑发热，因为哪些功能真的很好用，我觉得我不反对你得设计，我只是觉得这个功能在开发中是迫切需要得，因为它能减少大量得工作。

## 我迫切需要这些功能，因为我在用开发项目，我喜欢imi，巨佬辛苦了

**Comment by Mjc960512** [comment]
### 下面一些例子，巨佬可以好好思考下

- 一个表，定义了很多关联，例如一个用户关联了资料，订单，收藏了商品，在查询订单的时候，如果和避免将收藏，资料也查询出来（在使用关联功能的情况下进行。）

- 还是上面的需求，但使用虚拟字段进行查询，但若一个表定义了很多虚拟字段，是否可以通过dbQuery()->field()控制显示某些字段，以免将虚拟字段全部查出来，避免没有必要的性能浪费。

- 一对多关联，如果进行统计查询，关联中使用count()和where()，是否有解决方法？(在使用关联的情况下，我知道不使用关联可以做到)

一时间很难想到特别多的应用场景，但应用场景一定不少，这些功能使用with，闭包传参都可以搞定，我相信老哥你也非常抵制996的，因为你在群里经常说的就是，抵制996，一把梭，我觉得你也在考虑灵活性上思考了很久，但没有with的设计，和你说的这些话变得有些违背。

我觉得所谓的哲学和现实情况并不矛盾，你可以考虑下是否可以在兼顾哲学的情况下，将这些恶心人的工作在用imi的时候变得无比轻松，而这种轻松在使用非swoole框架得时候，其实早就实现了，你的框架设计初衷，就是小而快，使用简单却灵活多变，我相信heyerf借鉴laravel也不是头脑发热，因为哪些功能真的很好用，我觉得我不反对你得设计，我只是觉得这个功能在开发中是迫切需要得，因为它能减少大量得工作。

## 我迫切需要这些功能，因为我在用开发项目，我喜欢imi，巨佬辛苦了

**Comment by Yurunsoft** [comment]
现已实现：模型查询时如果指定 field，模型对象序列化时不会把不相关字段返回

模型关联也支持了注解指定字段，文档：<https://doc.imiphp.com/components/orm/relation/index.html>
